insert into public.roles (name, description) values
  ('super_admin', 'Platform-level super administrator across offices.'),
  ('office_owner', 'Office owner with full governance controls.'),
  ('admin', 'Administrative manager for legal office operations.'),
  ('lawyer', 'Lawyer role with full legal workflow actions.'),
  ('trainee', 'Trainee role with supervised and non-confidential scope.'),
  ('finance', 'Finance role restricted to billing operations.'),
  ('secretary', 'Secretary role for scheduling, notifications, and support actions.'),
  ('client_portal', 'Client portal role with explicit-share access only.'),
  ('external_collaborator', 'External collaborator role with limited case visibility.'),
  ('owner', 'Legacy owner role mapped to office owner behavior.'),
  ('staff', 'Legacy staff role mapped to secretary behavior.'),
  ('client', 'Legacy client role mapped to client portal behavior.'),
  ('system', 'Service/system role for automation and background workflows.')
on conflict (name) do update set description = excluded.description;

insert into public.permissions (name, description) values
  ('create_proceeding', 'Create proceedings under a legal matter.'),
  ('create_appeal', 'Create appeal proceeding from first instance.'),
  ('create_cassation', 'Create cassation proceeding from appeal.'),
  ('open_execution', 'Open execution proceeding.'),
  ('upload_document', 'Upload or add document records and versions.'),
  ('approve_document', 'Approve/review legal documents.'),
  ('assign_users', 'Assign users to legal matters and workflows.'),
  ('close_matter', 'Close a legal matter.'),
  ('manage_billing', 'Manage invoices and billing operations.'),
  ('export_case', 'Export legal case/matter data.'),
  ('manage_clients', 'Manage clients and matter intake assignment.'),
  ('run_conflict_check', 'Run legal conflict checks.'),
  ('manage_hearings', 'Manage hearings and scheduling.'),
  ('manage_notifications', 'Manage timeline/client notifications.'),
  ('manage_users', 'Manage office users and role assignments.'),
  ('ai_privileged_actions', 'Run privileged AI legal analysis actions.')
on conflict (name) do update set description = excluded.description;

insert into public.role_permissions (role, permission)
select role_name::public.member_role, permission_name
from (
  values
    ('super_admin', 'create_proceeding'),
    ('super_admin', 'create_appeal'),
    ('super_admin', 'create_cassation'),
    ('super_admin', 'open_execution'),
    ('super_admin', 'upload_document'),
    ('super_admin', 'approve_document'),
    ('super_admin', 'assign_users'),
    ('super_admin', 'close_matter'),
    ('super_admin', 'manage_billing'),
    ('super_admin', 'export_case'),
    ('super_admin', 'manage_clients'),
    ('super_admin', 'run_conflict_check'),
    ('super_admin', 'manage_hearings'),
    ('super_admin', 'manage_notifications'),
    ('super_admin', 'manage_users'),
    ('super_admin', 'ai_privileged_actions'),

    ('office_owner', 'create_proceeding'),
    ('office_owner', 'create_appeal'),
    ('office_owner', 'create_cassation'),
    ('office_owner', 'open_execution'),
    ('office_owner', 'upload_document'),
    ('office_owner', 'approve_document'),
    ('office_owner', 'assign_users'),
    ('office_owner', 'close_matter'),
    ('office_owner', 'manage_billing'),
    ('office_owner', 'export_case'),
    ('office_owner', 'manage_clients'),
    ('office_owner', 'run_conflict_check'),
    ('office_owner', 'manage_hearings'),
    ('office_owner', 'manage_notifications'),
    ('office_owner', 'manage_users'),
    ('office_owner', 'ai_privileged_actions'),

    ('admin', 'create_proceeding'),
    ('admin', 'create_appeal'),
    ('admin', 'create_cassation'),
    ('admin', 'open_execution'),
    ('admin', 'upload_document'),
    ('admin', 'approve_document'),
    ('admin', 'assign_users'),
    ('admin', 'close_matter'),
    ('admin', 'manage_billing'),
    ('admin', 'export_case'),
    ('admin', 'manage_clients'),
    ('admin', 'run_conflict_check'),
    ('admin', 'manage_hearings'),
    ('admin', 'manage_notifications'),
    ('admin', 'manage_users'),
    ('admin', 'ai_privileged_actions'),

    ('lawyer', 'create_proceeding'),
    ('lawyer', 'create_appeal'),
    ('lawyer', 'create_cassation'),
    ('lawyer', 'open_execution'),
    ('lawyer', 'upload_document'),
    ('lawyer', 'approve_document'),
    ('lawyer', 'assign_users'),
    ('lawyer', 'close_matter'),
    ('lawyer', 'export_case'),
    ('lawyer', 'manage_clients'),
    ('lawyer', 'run_conflict_check'),
    ('lawyer', 'manage_hearings'),
    ('lawyer', 'manage_notifications'),
    ('lawyer', 'ai_privileged_actions'),

    ('trainee', 'create_proceeding'),
    ('trainee', 'upload_document'),
    ('trainee', 'export_case'),
    ('trainee', 'run_conflict_check'),
    ('trainee', 'manage_hearings'),
    ('trainee', 'manage_notifications'),

    ('finance', 'manage_billing'),
    ('finance', 'export_case'),

    ('secretary', 'create_proceeding'),
    ('secretary', 'upload_document'),
    ('secretary', 'manage_hearings'),
    ('secretary', 'manage_notifications'),
    ('secretary', 'export_case'),

    ('client_portal', 'upload_document'),

    ('external_collaborator', 'export_case'),
    ('external_collaborator', 'run_conflict_check'),

    ('system', 'create_proceeding'),
    ('system', 'create_appeal'),
    ('system', 'create_cassation'),
    ('system', 'open_execution'),
    ('system', 'upload_document'),
    ('system', 'approve_document'),
    ('system', 'assign_users'),
    ('system', 'close_matter'),
    ('system', 'manage_billing'),
    ('system', 'export_case'),
    ('system', 'manage_clients'),
    ('system', 'run_conflict_check'),
    ('system', 'manage_hearings'),
    ('system', 'manage_notifications'),
    ('system', 'manage_users'),
    ('system', 'ai_privileged_actions'),

    ('owner', 'create_proceeding'),
    ('owner', 'create_appeal'),
    ('owner', 'create_cassation'),
    ('owner', 'open_execution'),
    ('owner', 'upload_document'),
    ('owner', 'approve_document'),
    ('owner', 'assign_users'),
    ('owner', 'close_matter'),
    ('owner', 'manage_billing'),
    ('owner', 'export_case'),
    ('owner', 'manage_clients'),
    ('owner', 'run_conflict_check'),
    ('owner', 'manage_hearings'),
    ('owner', 'manage_notifications'),
    ('owner', 'manage_users'),
    ('owner', 'ai_privileged_actions'),

    ('staff', 'create_proceeding'),
    ('staff', 'upload_document'),
    ('staff', 'manage_hearings'),
    ('staff', 'manage_notifications'),
    ('staff', 'export_case'),

    ('client', 'upload_document')
) as grants(role_name, permission_name)
on conflict do nothing;
